language: java
sudo: required
dist: trusty

jdk:
  - openjdk8
  - oraclejdk8
  - openjdk11

branches:
  except:
    - /^v|d\d+\.\d+\.\d+$/
    - /^jenkins-veraPDF-pdfbox-validation-v|d\\d+\\.\\d+\\.\\d+$/
