language: java
sudo: required
dist: trusty

jdk:
  - openjdk8
  - oraclejdk8
  - openjdk11

branches:
  except:
    - /^v|d\d+\.\d+\.\d+$/
    - /^jenkins-veraPDF-pdfbox-validation-v|d\\d+\\.\\d+\\.\\d+$/

before_install:
  - sudo apt-get install jq
  - wget -O ~/codacy-coverage-reporter-assembly-latest.jar http://resources.openpreservation.org/codacy-coverage-reporter-assembly-latest.jar

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - java -cp ~/codacy-coverage-reporter-assembly-latest.jar com.codacy.CodacyCoverageReporter -l Java -r target/site/jacoco/jacoco.xml
